[[redirects]]
  from = "https://openiis-ui.netlify.app/*"
  to = "https://ui.openiis.org/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.openiis-ui.netlify.app/*"
  to = "https://ui.openiis.org/:splat"
  status = 301
  force = true